//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisement()
        {
            this.AdAttendance = new HashSet<AdAttendance>();
        }
    
        public int AdvId { get; set; }
        public string AdvContent { get; set; }
        public int StarId { get; set; }
        public int UsrId { get; set; }
        public int GoodId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdAttendance> AdAttendance { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual StarInfo StarInfo { get; set; }
        public virtual Usr Usr { get; set; }
    }
}
