//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunShow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FunShowEntities : DbContext
    {
        public FunShowEntities()
            : base("name=FunShowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Concern> Concern { get; set; }
        public virtual DbSet<GComment> GComment { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GReplyComment> GReplyComment { get; set; }
        public virtual DbSet<Leavewords> Leavewords { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Opus> Opus { get; set; }
        public virtual DbSet<OrderItems> OrderItems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Sponsor> Sponsor { get; set; }
        public virtual DbSet<StarInfo> StarInfo { get; set; }
        public virtual DbSet<Usr> Usr { get; set; }
        public virtual DbSet<VComments> VComments { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<VReplyComment> VReplyComment { get; set; }
        public virtual DbSet<AcAttendance> AcAttendance { get; set; }
        public virtual DbSet<AdAttendance> AdAttendance { get; set; }
    }
}
