//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GComment()
        {
            this.GReplyComment = new HashSet<GReplyComment>();
        }
    
        public int GComId { get; set; }
        public int GoodId { get; set; }
        public int UsrId { get; set; }
        public System.DateTime GComTime { get; set; }
        public string GComContent { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Usr Usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GReplyComment> GReplyComment { get; set; }
    }
}
