//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GReplyComment
    {
        public string GReplyId { get; set; }
        public System.DateTime GRepTime { get; set; }
        public string GRepContent { get; set; }
        public int UsrId { get; set; }
        public int GComId { get; set; }
    
        public virtual GComment GComment { get; set; }
        public virtual Usr Usr { get; set; }
    }
}
