//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opus()
        {
            this.StarInfo = new HashSet<StarInfo>();
        }
    
        public int OpusId { get; set; }
        public string OpusName { get; set; }
        public string OpusImage { get; set; }
        public Nullable<System.DateTime> ShowTime { get; set; }
        public string OType { get; set; }
        public string link { get; set; }
        public int StarId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StarInfo> StarInfo { get; set; }
    }
}
