//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int SponId { get; set; }
        public string SponTitle { get; set; }
        public string SponContent { get; set; }
        public string SponImage { get; set; }
        public System.DateTime SponBeginTime { get; set; }
        public System.DateTime SponEndTime { get; set; }
        public string SponEmail { get; set; }
    }
}
