//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StarInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StarInfo()
        {
            this.Advertisement = new HashSet<Advertisement>();
        }
    
        public int StarId { get; set; }
        public string StarName { get; set; }
        public string SSex { get; set; }
        public Nullable<System.DateTime> SBirth { get; set; }
        public int OpusId { get; set; }
        public int NewsId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisement> Advertisement { get; set; }
        public virtual News News { get; set; }
        public virtual Opus Opus { get; set; }
    }
}
