//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.VReplyComment = new HashSet<VReplyComment>();
        }
    
        public int VideoId { get; set; }
        public int UsrId { get; set; }
        public string VTitle { get; set; }
        public string VContent { get; set; }
        public string VType { get; set; }
        public Nullable<System.DateTime> VUploadTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Usr Usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VReplyComment> VReplyComment { get; set; }
    }
}
